version: '3'

services:
  chain-node:
    container_name: ${NODE_CONTAINER_NAME}
    build:
      context: ./docker
      dockerfile: Dockerfile
      args:
        NODE_BINARY_NAME: ${NODE_BINARY_NAME}
        NODE_BINARY_URL: ${NODE_BINARY_URL}
        COSMOVISOR_BINARY_URL: ${COSMOVISOR_BINARY_URL:-}
    restart: always
    environment:
      - NODE_MONIKER=${NODE_MONIKER}
      - NODE_CONTAINER_NAME=${NODE_CONTAINER_NAME}
      - CHAIN_ID=${CHAIN_ID}
      - CHAIN_GENESIS_URL=${CHAIN_GENESIS_URL}
      - CHAIN_SNAPSHOT_URL=${CHAIN_SNAPSHOT_URL:-}
      - CHAIN_ADDRBOOK_URL=${CHAIN_ADDRBOOK_URL:-}
      - SEED_HOSTS=${SEED_HOSTS:-}
      - PERSISTENT_PEER_HOSTS=${PERSISTENT_PEER_HOSTS:-}

      - EXTERNAL_IP=${EXTERNAL_IP}
      - EXPOSE_P2P_PORT=${EXPOSE_P2P_PORT:-}
      - EXPOSE_RPC_PORT=${EXPOSE_RPC_PORT:-}
      - EXPOSE_GRPC_PORT=${EXPOSE_GRPC_PORT:-}
      - EXPOSE_GRPC_WEB_PORT=${EXPOSE_GRPC_WEB_PORT:-}
      - EXPOSE_API_PORT=${EXPOSE_API_PORT:-}
      - SEEDS_P2P_PORT=${SEEDS_P2P_PORT:-}
      - SEEDS_RPC_PORT=${SEEDS_RPC_PORT:-}

      - NODE_P2P_ADDR_BOOK_STRICT=${NODE_P2P_ADDR_BOOK_STRICT:-false}
      - NODE_SEED_MODE=${NODE_SEED_MODE:-false}
      - NODE_P2P_PEX=${NODE_P2P_PEX:-true}

      - NODE_STATESYNC=${NODE_STATESYNC:-false}
      - NODE_STATESYNC_TRUST_RPC=${NODE_STATESYNC_TRUST_RPC:-}
      - NODE_STATESYNC_RPC_SERVERS=${NODE_STATESYNC_RPC_SERVERS:-}
      - NODE_STATESYNC_TRUST_HEIGHT=${NODE_STATESYNC_TRUST_HEIGHT:-}
      - NODE_STATESYNC_TRUST_HASH=${NODE_STATESYNC_TRUST_HASH:-}

      - RPC_CORS_ALLOWED_ORIGINS=${RPC_CORS_ALLOWED_ORIGINS:-}

      - NODE_API_SWAGGER=${NODE_API_SWAGGER:-false}

      - COMPARE_NODES=${COMPARE_NODES:-}
      - NODE_POLL_INTERVAL_SECONDS=${NODE_POLL_INTERVAL_SECONDS:-}
      - NODE_RESTART_HEIGHT_DIFF=${NODE_RESTART_HEIGHT_DIFF:-}
      - NODE_RESTART_CMD=${NODE_RESTART_CMD:-}
      - DISCORD_WEBHOOK=${DISCORD_WEBHOOK:-}
    ports:
      - ${EXPOSE_P2P_PORT:-127.0.0.1:0}:${EXPOSE_P2P_PORT:-26656}
      - ${EXPOSE_RPC_PORT:-127.0.0.1:0}:${EXPOSE_RPC_PORT:-26657}
      - ${EXPOSE_GRPC_PORT:-127.0.0.1:0}:${EXPOSE_GRPC_PORT:-9191}
      - ${EXPOSE_GRPC_WEB_PORT:-127.0.0.1:0}:${EXPOSE_GRPC_WEB_PORT:-9091}
      - ${EXPOSE_API_PORT:-127.0.0.1:0}:${EXPOSE_API_PORT:-1317}
    volumes:
      - ./chain/:/chain/
  